### ISSUE TITLE
Installation aborted because the add-on appears to be corrupt

### ISSUE THREAD

**Issue by grahamperrin** [sereneblue/chrono#142]
![installation aborted](https://user-images.githubusercontent.com/192271/69833953-0c755380-122f-11ea-8ad2-08be743c1573.png)

In the browser console: 

`1574980246057	addons.webextension.<unknown>	ERROR	Loading extension 'null': Reading manifest: Error processing commands.openOptionsPage.suggested_key.default: Value "Ctrl+Alt+H" must either: match the pattern /^\s*(Alt|Ctrl|Command|MacCtrl)\s*\+\s*(Shift\s*\+\s*)?([A-Z0-9]|Comma|Period|Home|End|PageUp|PageDown|Space|Insert|Delete|Up|Down|Left|Right)\s*$/, match the pattern /^\s*((Alt|Ctrl|Command|MacCtrl)\s*\+\s*)?(Shift\s*\+\s*)?(F[1-9]|F1[0-2])\s*$/, or match the pattern /^(MediaNextTrack|MediaPlayPause|MediaPrevTrack|MediaStop)$/`

Home-built Waterfox Classic 2019.10 (20191103135811), FreeBSD-CURRENT.

**Comment by sereneblue** [comment]
Hi @grahamperrin,

It seems this is a Waterfox Classic issue; Ctrl+Alt+H is not considered a valid shortcut. I'd use Ctrl+Shift+H to open the extension but it's already used by Firefox to open the library dialog. It's probably best to bring this up to the Waterfox community.

**Comment by grahamperrin** [comment]
Thanks ∴ https://redd.it/e3fhoh
