### ISSUE TITLE
Keyboard shortcut - Ctrl+H

### ISSUE THREAD

**Issue by iamsenthilprabu** [sereneblue/chrono#3]
Is it possible to implement a custom keyboard shortcut? 
With existing firefox 'manage extension shortcuts' - It is possible to assign a shortcut key - but not possible to change the existing firefox key (Ctrl + H) - It will be nice if we could do this.

As of now, (as an alternative solution) I am using the Shortkeys (https://addons.mozilla.org/en-US/firefox/addon/shortkeys/ - https://github.com/mikecrittenden/shortkeys) extension to do this.

Thanks :)

**Comment by sereneblue** [comment]
There is a keyboard shortcut, `CTRL+ALT+H`. `CTRL+H` is an existing shortcut that opens the history sidebar. I'll update the readme/UI to mention that. Thanks!

You can also change the shortcut by going to `about:addons`, clicking the settings dropdown button and clicking `Manage Extension Shortcuts`.
