### ISSUE TITLE
No history is tracked in the "private" mode

### ISSUE THREAD

**Issue by asvc** [sereneblue/chrono#432]
No history is tracked in the "private" mode. "Run in private windows" is set to True:
![image](https://user-images.githubusercontent.com/300146/91250834-7fbdde80-e749-11ea-9cee-c1a29cbeb6ce.png)

For what it's worth, [Chameleon](https://github.com/sereneblue/chameleon ) is running in the same FF instance.

**Comment by sereneblue** [comment]
Hi @asvc,

Only the history made in non-private windows is tracked; that's how Firefox works. You can verify this by viewing your browser history and browsing pages in private/non-private windows.
